### ISSUE TITLE
Version 2.0 Checklist

### ISSUE THREAD

**Issue by tylucaskelley** [tylucaskelley/dotfiles#77]
This will be a complete re-write! Moving from Bash to Python in most places, publishing to PyPi, a real CLI, a test suite, configuration options, and more. With that comes a lot of stuff to do:

### General

- [ ] Logging and other helper utilities
- [ ] Come up with option groups and figure out which features of my setup go into them, and which features should be a part of the base installation
- [ ] Support dotfile templates

### Dotfiles

- [ ] Support for string templates so that dotfiles can include or exclude code based on user choices
- [ ] Get latest dotfiles from my setup

### Vim/Neovim, Tmux, iTerm

- [ ] Switch everything over to Neovim but keep .vimrc as main config file
- [ ] Tmux and iTerm require some additional setup (installing TPM plugins, loading iTerm config), so just take care to make sure that all happens smoothly

### Package Installation

- [ ] Related to option groups; decide on what languages, if any, are required, how they should be installed (rvm vs rbenv, etc), and what packages should be installed by default (if any)
- [ ] Support more languages, and support current ones better (outside of node and python support is weak right now)

### Interface

- [ ] Decide on click framework vs other options
- [ ] Decide on balance between CLI flags (good for automated testing) vs. amount of in-app options

## Test Suite

- [ ] 100% code coverage
- [ ] See what can be tested given need for user password input
- [ ] Travis CI possible??

## Misc.

- [ ] Nice logo
- [ ] Advertise a lot on Hacker News, FB groups, etc.
